update next dockerfile

diff --git a/next-app/Dockerfile b/next-app/Dockerfile
--- a/next-app/Dockerfile
+++ b/next-app/Dockerfile
@@ -1,26 +1,31 @@
-# layer 1
-FROM node:lts as dependencies
-WORKDIR /app
-COPY package.json package-lock.json ./
-RUN npm install --frozen-lockfile
 
-# layer 2
-FROM node:lts as builder
+FROM node:16-alpine AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-COPY --from=dependencies /app/node_modules ./node_modules
-RUN npm run build
+RUN yarn build
 
-# layer 3
-FROM node:lts as runner
+FROM node:16-alpine AS runner
 WORKDIR /app
 ENV NODE_ENV production
-
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
 COPY --from=builder /app/public ./public
-COPY --from=builder /app/.next ./.next
-COPY --from=builder /app/node_modules ./node_modules
-COPY --from=builder /app/package.json ./package.json
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
 
-# run
+USER nextjs
 EXPOSE 3000
-CMD ["npm", "start"]
+ENV PORT 3000
+CMD ["node", "server.js"]
